import { Match, Sport } from "./types";

export const SPORTS: Sport[] = [
  {
    id: "football",
    name: "FOOTBALL",
    icon: "Soccer",
    count: 1828,
    countries: [
      { name: "England", count: 142 },
      { name: "Spain", count: 120 },
      { name: "Italy", count: 98 },
      { name: "Germany", count: 85 },
      { name: "France", count: 77 },
      { name: "Portugal", count: 45 },
      { name: "Netherlands", count: 40 },
    ],
  },
  {
    id: "basketball",
    name: "BASKETBALL",
    icon: "Basketball",
    count: 258,
    countries: [
      { name: "USA", count: 88 },
      { name: "Spain", count: 32 },
      { name: "Turkey", count: 24 },
      { name: "Greece", count: 18 },
    ],
  },
  {
    id: "tennis",
    name: "TENNIS",
    icon: "Trophy",
    count: 3,
    countries: [
      { name: "ATP", count: 2 },
      { name: "WTA", count: 1 },
    ],
  },
  {
    id: "volleyball",
    name: "VOLLEYBALL",
    icon: "Activity",
    count: 37,
    countries: [
      { name: "Italy", count: 12 },
      { name: "Poland", count: 8 },
    ],
  },
  {
    id: "hockey",
    name: "ICE HOCKEY",
    icon: "Snowflake",
    count: 49,
    countries: [
      { name: "USA", count: 25 },
      { name: "Russia", count: 14 },
    ],
  },
  {
    id: "cricket",
    name: "CRICKET",
    icon: "Stick",
    count: 35,
    countries: [
      { name: "India", count: 15 },
      { name: "Australia", count: 10 },
    ],
  },
  {
    id: "handball",
    name: "HANDBALL",
    icon: "Hand",
    count: 88,
    countries: [
      { name: "Germany", count: 30 },
      { name: "Denmark", count: 22 },
    ],
  },
  {
    id: "baseball",
    name: "BASEBALL",
    icon: "Circle",
    count: 40,
    countries: [
      { name: "USA", count: 35 },
      { name: "Japan", count: 5 },
    ],
  },
];

export const TOP_LEAGUES = [
  { name: "World - FIFA World Cup 2026", country: "World" },
  { name: "Europe - UEFA Champions League", country: "Europe" },
  { name: "England - Premier League", country: "England" },
  { name: "Spain - La Liga", country: "Spain" },
  { name: "Italy - Serie A", country: "Italy" },
  { name: "Germany - Bundesliga", country: "Germany" },
  { name: "France - Ligue 1", country: "France" },
];

export const MATCHES: Match[] = [
  {
    id: "1",
    country: "Spain",
    league: "La Liga",
    homeTeam: "Villarreal",
    awayTeam: "Levante",
    date: "02/05",
    time: "15:00",
    odds: {
      home: 1.65,
      draw: 4.09,
      away: 4.24,
      dc1x: 1.18,
      dc12: 1.2,
      dcx2: 2.04,
      btsYes: 1.58,
      btsNo: 2.22,
    },
  },
  {
    id: "2",
    country: "Italy",
    league: "Serie A",
    homeTeam: "Udinese Calcio",
    awayTeam: "Torino",
    date: "02/05",
    time: "16:00",
    odds: {
      home: 2.24,
      draw: 3.1,
      away: 3.17,
      dc1x: 1.3,
      dc12: 1.32,
      dcx2: 1.55,
      btsYes: 1.79,
      btsNo: 1.9,
    },
  },
  {
    id: "3",
    country: "France",
    league: "Ligue 1",
    homeTeam: "FC Nantes",
    awayTeam: "Olympique Marseille",
    date: "02/05",
    time: "16:00",
    odds: {
      home: 4.18,
      draw: 3.86,
      away: 1.71,
      dc1x: 1.97,
      dc12: 1.22,
      dcx2: 1.19,
      btsYes: 1.59,
      btsNo: 2.2,
    },
  },
  {
    id: "4",
    country: "Europe",
    league: "UEFA Champions League Women",
    homeTeam: "Olympique Lyonnais W",
    awayTeam: "Arsenal Women",
    date: "02/05",
    time: "16:00",
    odds: {
      home: 1.55,
      draw: 4.05,
      away: 4.66,
      dc1x: 1.13,
      dc12: 1.17,
      dcx2: 2.13,
      btsYes: 1.57,
      btsNo: 2.14,
    },
  },
  {
    id: "5",
    country: "Europe",
    league: "UEFA Champions League Women",
    homeTeam: "Olympique Lyonnais W",
    awayTeam: "Arsenal Women",
    date: "02/05",
    time: "16:00",
    odds: {
      home: 1.55,
      draw: 4.05,
      away: 4.66,
      dc1x: 1.13,
      dc12: 1.17,
      dcx2: 2.13,
      btsYes: 1.57,
      btsNo: 2.14,
    },
  },
];
